### ISSUE TITLE
Stuck at: apple nvme assert failed

### ISSUE THREAD

**Issue by nguyenduyphuonghh** [oscarrock/hackintosh-msi-gf63-thin-9SC#2]
Hi, I cannot boot up installation. My samsung ssd is running windows
Did you have built-in samsung nvme ssd installed when u boot up?

**Comment by oscarrock** [comment]
No i use a kingston ssd. I have read that samsung evo has several issues with hackintosh, you can search in tonymac posts or other pots using your hdd device vendor codes.

**Comment by nguyenduyphuonghh** [comment]
Hi, I've found solution from tonymacx86 which work almost full except for hdmi port. 
U can take a look at: 
<a>https://www.tonymacx86.com/threads/msi-gf63-thin-9sc.290000/</a>
