### ISSUE TITLE
Can You Help Me?

### ISSUE THREAD

**Issue by sirepson** [oscarrock/hackintosh-msi-gf63-thin-9SC#3]
I have Laptop HP PAVILION GAMING 15, the spec look like your Laptop.
- i7-9750H
- GTX1650/UHD630
- Elan Touchpad
- Intel Wireless
I'm use your EFI and change the config.plit, everything okay. But, the installer stuck.
Can you help me?
I try to ask in Olarila Forum but same problem.
https://www.olarila.com/topic/7774-service-exited-with-abnormal-code-1/?
![IMG_20200305_095503_compress49](https://user-images.githubusercontent.com/45273945/75948332-cdae0400-5ed5-11ea-8eed-3de24a5c1de0.jpg)

**Comment by sirepson** [comment]
Stuck in "about 2 minutes remaining". And after that reboot

**Comment by sirepson** [comment]
This is my BIOS SETTINGS, maybe I'm forget something
https://ibb.co/album/cVpDAa

**Comment by oscarrock** [comment]
Hey buddy, sorry. I am no expert in hackintosh. What i can say to you its to search a forum in tonymac or other hackintosh forums and search your laptop model to find proper config.plist for your hardware. If you want to ask to about an error. You should upload at least the log of your boot with clover or any logs of the crashes you find
